#version 450

layout(constant_id = 0) const int HANDLE_BLOCK_SIZE = 1;
layout(constant_id = 1) const int DATA_LENGTH = 1;

layout(local_size_x_id = 0) in;
layout(binding = 0) buffer HandleWindow {
  double handleW[];
};

layout(push_constant) uniform PushConstants {
  int call_index;
} pcs;

void main() {
  int index = pcs.call_index * HANDLE_BLOCK_SIZE + int(gl_LocalInvocationIndex);
  if (index >= DATA_LENGTH) return;
  handleW[index] /= sqrt(handleW[DATA_LENGTH]);
}
